project:
  base:
    url: /voting
  kafka:
    topic:
      partitions: 3
      replicas: 3
    enabled: true
  static:
    location:
      creation:
        enabled: false
server:
  port: 8083
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  data:
    mongodb:
      uri: mongodb+srv://jeetmazumdar:89Hu872nWCrVB5VZ@cluster0.yu8p2jp.mongodb.net/?retryWrites=true&w=majority
      database: homesecurity
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  kafka:
    admin:
      bootstrap:
        servers: localhost:9094,localhost:9095,localhost:9096
    consumer:
      bootstrap-servers: localhost:9094,localhost:9095,localhost:9096
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
        #properties:
        # spring:
        #  json:
        #   trusted:
      #    packages=*:
    producer:
      bootstrap-servers: localhost:9094,localhost:9095,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
